import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const browser = await chromium.launch({ headless: true, args: ['--use-gl=angle', '--use-angle=swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 });
page.setDefaultTimeout(60000);
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await page.goto(process.env.SIM_URL || 'http://localhost:5173', { waitUntil: 'domcontentloaded' });
await page.waitForFunction(() => typeof window.advanceTime === 'function');
await page.waitForTimeout(1500);
const state = () => page.evaluate(() => JSON.parse(window.render_game_to_text()));
const advance = ms => page.evaluate(ms => window.advanceTime(ms), ms);
const click = id => page.locator(id).click({ force: true, timeout: 15000 });
await fs.mkdir('output/validation', { recursive: true });
await page.screenshot({ path: 'output/validation/01-request.png', timeout: 15000 }).catch(() => {});
await click('#request');
assert.equal((await state()).phase, 'dispatch');
await click('#cancel');
assert.equal((await state()).phase, 'explore');
await click('#request');
await advance(14000);
assert.equal((await state()).phase, 'pickup');
assert.equal((await state()).megalamp, 'Violet');
assert.equal((await state()).geofence, true);
await page.screenshot({ path: 'output/validation/02-pickup.png', timeout: 15000 }).catch(() => {});
await click('#enter');
await advance(2000);
assert.equal((await state()).phase, 'boarded');
await click('#temp-up');
assert.equal((await state()).temperature, 22);
await click('#temp-down');
assert.equal((await state()).temperature, 21);
await click('#music');
assert.equal(await page.locator('#start-ride').isDisabled(), true);
await click('#buckle');
assert.equal((await state()).belted, true);
await advance(1500);
await click('#start-ride');
await advance(4000);
assert.equal((await state()).phase, 'ride');
assert.ok((await state()).distance > 0);
await click('#pause');
await advance(2500);
const stopped = (await state()).distance;
await advance(2000);
assert.equal((await state()).distance, stopped);
await click('#pause');
await advance(4000);
assert.ok((await state()).distance > stopped);
await page.screenshot({ path: 'output/validation/03-cabin.png', timeout: 15000 }).catch(() => {});
await advance(180000);
assert.equal((await state()).phase, 'arrived');
await page.screenshot({ path: 'output/validation/04-arrived.png', timeout: 15000 }).catch(() => {});
await click('#exit-cabin');
assert.equal((await state()).phase, 'exited');
await click('#finish');
assert.equal((await state()).phase, 'complete');
await click('#restart');
assert.equal((await state()).phase, 'explore');
assert.ok((await state()).distance > 0);
await page.keyboard.press('p');
assert.equal(await page.locator('#phone').isVisible(), false);
await page.keyboard.press('p');
assert.equal(await page.locator('#phone').isVisible(), true);
await page.setViewportSize({ width: 390, height: 844 });
await page.screenshot({ path: 'output/validation/05-mobile.png', timeout: 15000 }).catch(() => {});
assert.deepEqual(errors, []);
console.log('PASS: request/cancel, pickup, board, climate, audio, start, pause/resume, arrival, exit, restart, phone, megalamp, geofence, responsive. No page errors.');
await browser.close();
