import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});
page.setDefaultTimeout(60000);const errors=[];page.on('pageerror',error=>errors.push(error.message));
await page.goto(process.env.SIM_URL || 'http://localhost:5173');await page.waitForFunction(()=>typeof window.advanceTime==='function');await page.waitForTimeout(3000);
const state=()=>page.evaluate(()=>JSON.parse(window.render_game_to_text()));
const advance=ms=>page.evaluate(ms=>window.advanceTime(ms),ms);
await fs.mkdir('output/validation',{recursive:true});
await page.screenshot({path:'output/validation/01-request.png'});
await page.click('#request');assert.equal((await state()).phase,'dispatch');
await page.click('#cancel');assert.equal((await state()).phase,'explore');
await page.click('#request');await advance(14000);assert.equal((await state()).phase,'pickup');
assert.equal((await state()).megalamp,'Violet');
assert.equal((await state()).geofence,true);
await page.screenshot({path:'output/validation/02-pickup.png'});
await page.click('#enter');await advance(2000);assert.equal((await state()).phase,'boarded');
await page.click('#temp-up');assert.equal((await state()).temperature,22);
await page.click('#temp-down');assert.equal((await state()).temperature,21);
await page.click('#music');assert.equal(await page.locator('#start-ride').isDisabled(),true);await page.click('#buckle');assert.equal((await state()).belted,true);await page.click('#start-ride');await advance(4000);
assert.equal((await state()).phase,'ride');assert.ok((await state()).distance>0);
await page.click('#pause');const distance=(await state()).distance;await advance(3000);assert.equal((await state()).distance,distance);
await page.click('#pause');await advance(1000);assert.ok((await state()).distance>distance);
await page.screenshot({path:'output/validation/03-cabin.png'});
await advance(120000);assert.equal((await state()).phase,'arrived');
await page.screenshot({path:'output/validation/04-arrived.png'});
await page.click('#exit');assert.equal((await state()).phase,'complete');
await page.click('#restart');assert.equal((await state()).phase,'explore');assert.equal((await state()).distance,0);
await page.keyboard.press('p');assert.equal(await page.locator('#phone').isVisible(),false);await page.keyboard.press('p');assert.equal(await page.locator('#phone').isVisible(),true);
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'output/validation/05-mobile.png'});
assert.deepEqual(errors,[]);console.log('PASS: request/cancel, pickup, board, climate, audio, start, pause/resume, arrival, exit, restart, phone, responsive render. No page errors.');
await browser.close();
