import * as THREE from 'three';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
import { Sky } from 'three/addons/objects/Sky.js';
import { createWorld } from './world';
import { createCybercab } from './vehicle';
import './style.css';

type Phase = 'explore'|'dispatch'|'pickup'|'boarded'|'ride'|'arrived'|'complete';
const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML=`<canvas id="scene"></canvas><div class="vignette"></div>
<header><a class="brand" href="./"><span class="brand-icon">C</span> CYBERCAB <span class="brand-sub">AUSTIN EXPERIENCE</span></a><div class="live"><i></i> AUSTIN, TX <span>30.2640° N · 97.7450° W</span></div><button id="settings" class="round" aria-label="Toggle graphics quality">◈</button></header>
<aside class="chapter"><span class="eyebrow">THE CITY IS YOURS</span><h1>A different<br>way to move.</h1><p>Golden hour. Downtown Austin.<br>Your next ride is a little extraordinary.</p><div class="chapter-line"></div><span class="small-label">01 / REQUEST YOUR RIDE</span></aside>
<div class="location"><span class="location-dot">⌖</span><div><b id="location-name">Congress Avenue</b><span id="location-detail">DOWNTOWN · AUSTIN, TEXAS</span></div></div>
<aside id="phone" class="phone"><div class="phone-top"><b>6:42</b><div class="island"></div><span>▥ ▰</span></div><div class="phone-content"><div class="app-brand">ROBOTAXI <span>✦</span></div><div id="phone-body"></div></div><div class="home-bar"></div></aside>
<section id="cabin" class="cabin-panel" hidden></section>
<div id="toast" role="status"></div>
<footer><div class="controls"><span><kbd>DRAG</kbd> Look around</span><span><kbd>W A S D</kbd> Walk</span><span><kbd>P</kbd> Phone</span><span><kbd>F</kbd> Fullscreen</span></div><div class="concept">INDEPENDENT CONCEPT SIMULATION <span>·</span> <a href="https://www.openstreetmap.org/copyright" target="_blank">© OpenStreetMap</a><a href="./docs.html" target="_blank">Sources & accuracy ↗</a></div></footer>
<div class="ride-progress"><div id="progress-fill"></div></div>`;
const canvas=document.querySelector<HTMLCanvasElement>('#scene')!;
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
const scene=new THREE.Scene();scene.background=new THREE.Color('#becbd0');scene.fog=new THREE.FogExp2('#b9c4ca',.0007);
const camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.08,5000);
const sky=new Sky();sky.scale.setScalar(45000);const su=sky.material.uniforms;su.turbidity.value=3;su.rayleigh.value=1.2;su.mieCoefficient.value=.004;su.mieDirectionalG.value=.8;const sunPosition=new THREE.Vector3(-.7,.42,.3);su.sunPosition.value.copy(sunPosition);scene.add(sky);
const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(sky as unknown as THREE.Scene,.04).texture;
scene.add(new THREE.HemisphereLight('#d9eafa','#aa967d',1.3));const sun=new THREE.DirectionalLight('#ffe3ba',3.5);sun.position.set(-160,190,120);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-110;sun.shadow.camera.right=110;sun.shadow.camera.top=110;sun.shadow.camera.bottom=-110;sun.shadow.camera.far=650;sun.shadow.bias=-.0003;scene.add(sun);scene.add(sun.target);
const world=createWorld(scene);const cab=createCybercab();scene.add(cab.group);
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));composer.addPass(new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),.13,.4,.92));composer.addPass(new OutputPass());
const project=(lon:number,lat:number)=>new THREE.Vector3((lon+97.745)*96100,0,-(lat-30.264)*111320);
// Congress Avenue: measured OSM corridor. Route replaced with source geometry when loaded.
let route=[[-97.7442121, 30.2643199], [-97.7441843, 30.2643968], [-97.7438918, 30.2651707], [-97.7438737, 30.265219], [-97.7438534, 30.2652726], [-97.7438378, 30.265315], [-97.7438209, 30.26536], [-97.7437609, 30.2655204], [-97.7435465, 30.2660935], [-97.7435056, 30.266203], [-97.7434763, 30.2662811], [-97.743409, 30.2664611], [-97.7431938, 30.2670367], [-97.7431556, 30.2671385], [-97.7431271, 30.267215], [-97.7430377, 30.2674537], [-97.7429788, 30.2676111], [-97.7428453, 30.267968], [-97.7428064, 30.268072], [-97.7427783, 30.2681477], [-97.7424976, 30.2688977], [-97.7424606, 30.2689964]].map(([lon,lat])=>project(lon,lat).add(new THREE.Vector3(4.7,0,1.5)));
let cumulative:number[]=[];let routeLength=0;function measure(){cumulative=[0];routeLength=0;for(let i=1;i<route.length;i++){routeLength+=route[i].distanceTo(route[i-1]);cumulative.push(routeLength);}}measure();
function sample(distance:number){let i=1;while(i<cumulative.length-1 && cumulative[i]<distance)i++;const t=THREE.MathUtils.clamp((distance-cumulative[i-1])/(cumulative[i]-cumulative[i-1]),0,1);return {position:route[i-1].clone().lerp(route[i],t),heading:Math.atan2(-(route[i].x-route[i-1].x),-(route[i].z-route[i-1].z))};}
let phase:Phase='explore',belted=false,elapsed=0,distance=0,door=0,temperature=21,muted=false,phoneVisible=true,paused=false,lowQuality=false;
const pickup=sample(0);cab.group.position.copy(pickup.position);cab.group.rotation.y=pickup.heading;
let walk=pickup.position.clone().add(new THREE.Vector3(7,1.7,7));let yaw=.65,pitch=-.04;let last=performance.now();const keys=new Set<string>();
const phone=document.querySelector<HTMLElement>('#phone')!,body=document.querySelector<HTMLElement>('#phone-body')!,cabin=document.querySelector<HTMLElement>('#cabin')!;
let mapFeatures='';
const mapPoint=(v:THREE.Vector3)=>[140+(v.x-165)*.29,122+(v.z+300)*.29];
fetch(`${import.meta.env.BASE_URL}data/austin.json`).then(r=>r.json()).then(data=>{
 const path=(coords:number[][])=>coords.map(([lon,lat],i)=>{const [x,y]=mapPoint(project(lon,lat));return `${i?'L':'M'}${x.toFixed(1)},${y.toFixed(1)}`;}).join(' ');
 mapFeatures=data.buildings.map((b:{coordinates:number[][]})=>`<path d="${path(b.coordinates)}Z" fill="#d8dfd4"/>`).join('')+data.roads.map((r:{coordinates:number[][]})=>`<path d="${path(r.coordinates)}" fill="none" stroke="#fafbf7" stroke-width="3"/>`).join('');renderUI();
}).catch(()=>toast('Map unavailable. Showing the bundled route.'));
function mapMarkup(progress=0){
 const line=route.map((v,i)=>{const [x,y]=mapPoint(v);return `${i?'L':'M'}${x},${y}`;}).join(' ');
 const [px,py]=mapPoint(sample(progress*routeLength).position),[ex,ey]=mapPoint(route[route.length-1]);
 return `<div class="map"><svg viewBox="0 0 280 245"><rect width="280" height="245" fill="#e8ece4"/>${mapFeatures}<path d="${line}" stroke="#283d2e" stroke-width="4" fill="none" stroke-linecap="round"/><circle cx="${ex}" cy="${ey}" r="7" fill="#283d2e" stroke="white" stroke-width="3"/><circle cx="${px}" cy="${py}" r="8" fill="#c5a262" stroke="white" stroke-width="3"/><text x="155" y="58">DOWNTOWN</text><text x="25" y="232">CONGRESS AVENUE</text></svg><span class="map-pin">AUSTIN · N ↑</span><button class="map-expand" aria-label="Center map" id="center-map">⌖</button></div>`;
}
function setPhase(next:Phase){phase=next;elapsed=0;renderUI();}
function toast(text:string){document.querySelector('#toast')!.textContent=text;document.querySelector('#toast')!.classList.add('show');setTimeout(()=>document.querySelector('#toast')!.classList.remove('show'),2800);}
function renderUI(){
 document.querySelector('#location-name')!.textContent=phase==='complete'||phase==='arrived'?'Congress & 7th':'Congress & 2nd';
 const chapter=document.querySelector<HTMLElement>('.chapter')!;chapter.style.display=phase==='explore'?'block':'none';
 document.querySelector('.small-label')!.textContent='01 / REQUEST YOUR RIDE';
 phone.hidden=!phoneVisible || phase==='ride'||phase==='boarded';cabin.hidden=phase!=='ride'&&phase!=='boarded'&&phase!=='arrived';
 const map=mapMarkup(distance/routeLength);
 if(phase==='explore')body.innerHTML=`<h2>Where to?</h2><p class="phone-sub">A little less driving. A little more living.</p>${map}<div class="route-card"><div class="route-row"><i class="dot"></i><div><small>PICKUP</small><b>Congress & 2nd</b></div></div><div class="route-row"><i class="square"></i><div><small>DESTINATION</small><b>Congress & 7th</b></div><span>⌄</span></div></div><div class="fare"><span>Cybercab <small>2 seats · Simulated ride</small></span><b>~3 min<small>Simulated trip</small></b></div><button class="primary" id="request">Request Cybercab <span>↗</span></button><p class="micro">Independent recreation. No real booking or fare.</p>`;
 if(phase==='dispatch')body.innerHTML=`<h2>Your ride is on its way.</h2><p class="phone-sub">Meet your Cybercab at the curb.</p>${map}<div class="vehicle-card"><span class="car-line">▰</span><b>Gold Cybercab</b><small>CONCEPT VEHICLE · 02</small></div><div class="pickup-info"><i class="pulse"></i><div><b>Arriving shortly</b><small>Congress Avenue & 2nd Street</small></div></div><button class="secondary" id="cancel">Cancel request</button>`;
 if(phase==='pickup')body.innerHTML=`<h2>Your Cybercab is here.</h2><p class="phone-sub">The passenger door is open for you.</p>${map}<div class="vehicle-card"><span class="car-line">▰</span><b>Welcome aboard.</b><small>GOLD CYBERCAB · 2 SEATS</small></div><button class="primary" id="enter">Enter Cybercab <span>→</span></button><p class="micro">Step into your seat to begin.</p>`;
 if(phase==='arrived')body.innerHTML=`<h2>You have arrived.</h2><p class="phone-sub">Congress Avenue & 7th Street</p>${map}<div class="vehicle-card"><b>Make the city yours.</b><small>CHECK FOR YOUR BELONGINGS</small></div><button class="primary" id="exit">Exit Cybercab <span>→</span></button>`;
 if(phase==='complete')body.innerHTML=`<div class="complete-icon">✓</div><h2>Austin, at your pace.</h2><p class="phone-sub">Thanks for taking the scenic route.</p>${map}<div class="trip-summary"><span>Distance<b>${(routeLength/1000).toFixed(2)} km</b></span><span>Experience<b>Complete</b></span></div><button class="primary" id="restart">Take another ride <span>↗</span></button>`;
 if(phase==='boarded'||phase==='ride'||phase==='arrived')cabin.innerHTML=`<div class="cabin-header"><span>CYBERCAB</span><span>6:42 PM <i>☀</i> 28°</span></div><div class="cabin-grid"><div class="cabin-map">${map}</div><div class="cabin-copy"><small>${phase==='arrived'?'YOU HAVE ARRIVED':'YOUR DESTINATION'}</small><h2>Congress & 7th</h2><p>${phase==='boarded'?'Settle in. Your city awaits.':phase==='arrived'?'Check for belongings before leaving.':`${Math.max(1,Math.ceil((routeLength-distance)/180))} min · ${Math.max(0,(routeLength-distance)/1000).toFixed(2)} km remaining`}</p>${phase==='boarded'?`<button class="secondary" id="buckle">${belted?'✓ Seatbelt fastened':'Fasten seatbelt'}</button><button class="primary" id="start-ride" ${belted?'':'disabled'}>Start Ride →</button>`:phase==='arrived'?'<button class="primary" id="exit">Open door & exit →</button>':`<button class="secondary" id="pause">${paused?'Resume ride':'Pause simulation'}</button>`}</div></div><div class="cabin-bottom"><button id="temp-down" aria-label="Lower cabin temperature">−</button><b>${temperature}°</b><button id="temp-up" aria-label="Raise cabin temperature">+</button><span>AUTO</span><button id="music">${muted?'♫ Sound off':'♫ Ambient sound'}</button><span class="cabin-status">${phase==='ride'?'● RIDING AUTONOMOUSLY':'● READY'}</span></div>`;
 bind('request',()=>{cab.group.position.copy(sample(0).position).add(route[0].clone().sub(route[1]).normalize().multiplyScalar(35));setPhase('dispatch');});bind('cancel',()=>setPhase('explore'));bind('enter',()=>{yaw=.65;pitch=0;setPhase('boarded');});bind('buckle',()=>{belted=!belted;renderUI();});bind('start-ride',()=>{if(!belted)return;if(door>.02){toast('Waiting for the doors to close.');return;}startAudio();setPhase('ride');});bind('exit',()=>{walk=cab.group.position.clone().add(new THREE.Vector3(10,1.7,8));yaw=.7;pitch=-.04;phoneVisible=true;setPhase('complete');});bind('restart',()=>{distance=0;walk=pickup.position.clone().add(new THREE.Vector3(7,1.7,7));paused=false;belted=false;yaw=.65;pitch=-.04;setPhase('explore');});bind('pause',()=>{paused=!paused;renderUI();});bind('temp-down',()=>{temperature=Math.max(16,temperature-1);renderUI();});bind('temp-up',()=>{temperature=Math.min(28,temperature+1);renderUI();});bind('music',()=>{muted=!muted;if(gain)gain.gain.value=muted?0:.018;renderUI();});bind('center-map',()=>toast('Map centered on your simulated route.'));
}
function bind(id:string,fn:()=>void){document.getElementById(id)?.addEventListener('click',fn);}
let audio:AudioContext|undefined,gain:GainNode|undefined;function startAudio(){if(audio)return;audio=new AudioContext();gain=audio.createGain();gain.gain.value=.018;gain.connect(audio.destination);[110,164.81,220].forEach(f=>{const o=audio!.createOscillator();o.frequency.value=f;o.connect(gain!);o.start();});}
let dragging=false,lx=0,ly=0;canvas.addEventListener('pointerdown',e=>{dragging=true;lx=e.clientX;ly=e.clientY;canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointerup',()=>dragging=false);canvas.addEventListener('pointermove',e=>{if(!dragging)return;yaw-=(e.clientX-lx)*.003;pitch=THREE.MathUtils.clamp(pitch-(e.clientY-ly)*.003,-1,1);lx=e.clientX;ly=e.clientY;});
window.addEventListener('keydown',e=>{if(e.repeat)return;keys.add(e.key.toLowerCase());if(e.key.toLowerCase()==='p'){phoneVisible=!phoneVisible;renderUI();}if(e.key.toLowerCase()==='f'){if(document.fullscreenElement)void document.exitFullscreen();else void document.documentElement.requestFullscreen();}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>keys.clear());
bind('settings',()=>{lowQuality=!lowQuality;renderer.setPixelRatio(lowQuality?1:Math.min(devicePixelRatio,1.75));renderer.shadowMap.enabled=!lowQuality;toast(lowQuality?'Performance graphics enabled':'High graphics enabled');});
function update(dt:number){elapsed+=dt;world.update(dt);let speed=0;
 if(phase==='dispatch'){const target=sample(0).position;cab.group.position.lerp(target,1-Math.exp(-dt*.65));if(elapsed>8){cab.group.position.copy(target);setPhase('pickup');}}
 if(phase==='explore'){cab.group.position.copy(sample(0).position);}
 if(phase==='ride'&&!paused&&door<.02){speed=Math.min(10,elapsed*2,(routeLength-distance)*.7+1);distance=Math.min(routeLength,distance+speed*dt);const p=sample(distance);cab.group.position.copy(p.position);cab.group.rotation.y=p.heading;if(distance>=routeLength){phoneVisible=false;setPhase('arrived');}}
 door=THREE.MathUtils.damp(door,(phase==='pickup'||phase==='complete'||phase==='arrived')?1:0,3,dt);cab.setDoor(door);cab.update(dt,speed);
 if(phase==='boarded'||phase==='ride'||phase==='arrived'){const local=new THREE.Vector3(.35,1.18,.35);local.applyMatrix4(cab.group.matrixWorld);camera.position.lerp(local,1-Math.exp(-dt*5));camera.rotation.order='YXZ';camera.rotation.set(pitch,cab.group.rotation.y+(yaw-.65)*.5,0);}
 else{const movement=new THREE.Vector3(Number(keys.has('d'))-Number(keys.has('a')),0,Number(keys.has('s'))-Number(keys.has('w')));movement.applyAxisAngle(new THREE.Vector3(0,1,0),yaw).multiplyScalar(dt*5);walk.add(movement);camera.position.lerp(walk,1-Math.exp(-dt*5));camera.rotation.order='YXZ';camera.rotation.set(pitch,yaw,0);}
 sun.position.copy(cab.group.position).add(new THREE.Vector3(-160,190,120));sun.target.position.copy(cab.group.position);document.querySelector<HTMLElement>('#progress-fill')!.style.width=`${distance/routeLength*100}%`;}
let uiTimer=0;function animate(now:number){const dt=Math.min((now-last)/1000,.05);last=now;update(dt);uiTimer+=dt;if(phase==='ride'&&uiTimer>2){renderUI();uiTimer=0;}composer.render();requestAnimationFrame(animate);}renderUI();camera.position.copy(walk);requestAnimationFrame(animate);
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight);});
Object.assign(window,{render_game_to_text:()=>JSON.stringify({phase,belted,distance,totalDistance:routeLength,paused,temperature,door,position:camera.position.toArray(),coordinates:'meters; origin -97.745,30.264; X east, Y up, Z south',vehicle:cab.group.position.toArray()}),advanceTime:(ms:number)=>{for(let t=0;t<ms;t+=16.667)update(Math.min(16.667,ms-t)/1000);renderUI();composer.render();}});
